### ISSUE TITLE
File Encoding Not Consistent

### ISSUE THREAD

**Issue by nabber00** [wyrie/puppet-spamassassin#7]
init.pp is UTF-8 for some reason, causing this error:

Debug: catalog supports formats: pson msgpack yaml b64_zlib_yaml dot raw
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: invalid byte sequence in US-ASCII at /etc/puppet/modules/spamassassin/manifests/init.pp:1 on node 

file command confirms:

root@amargosa:/etc/puppet/modules/spamassassin# find . -name "*.pp" | xargs file
./tests/sql.pp:        C++ source, ASCII text
./tests/spamd.pp:      C++ source, ASCII text
./tests/init.pp:       C++ source, ASCII text
./manifests/params.pp: C++ source, ASCII text
./manifests/init.pp:   C source, UTF-8 Unicode text, with very long lines

Suggested fix is to change init.pp to ASCII.

**Comment by nabber00** [comment]
Fix on Linux:

root@amargosa:/etc/puppet/modules/spamassassin/manifests# iconv --from-code UTF-8 --to-code US-ASCII -c init.pp > init.new.pp

**Comment by wyrie** [comment]
What version of puppet are you running on your master? Is it apache+passenger?

**Comment by wyrie** [comment]
Changed in 97c639e
